bitcoin:
  rpc:
    host: 127.0.0.1
    port: 8332
    user: bitcoind-rpc-user
    password: bitcoind-rpc-password
server:
  rpc:
    user: your-custom-rpcuser
    passwd: your-private-rpcpassword
  log:
    level: debug
    log-path: logs
  db:
    driver: bboltdb
    bbolt:
      dbpath: .data/bitstate.db
    leveldb:
  task:
    end: 200000
  cache:
    utxo: 200000
    address: 300000