bitocin:
  rpc:
    host: 127.0.0.1
    port: 8332
    user: bitcoind-rpc-user
    password: bitcoind-rpc-password
server:
  rpc:
    user: your-custom-rpcuser
    passwd: your-private-rpcpassword
  log:
    level: debug
    log-path: logs
  db:
    dbpath: .data/bitstate.db
  task:
    start: 0
    end: 300000
  cache:
    utxo: 1000000
    address: 2000000
    utxo-sub: 200000
    address-sub: 300000